### ISSUE TITLE
missing "zobrazit" in headers

### ISSUE THREAD

**Issue by solumath** [GrillBot/GrillBot.Web#10]
it seems theres missing text "zobrazit" in those two headers for tables
![image](https://github.com/GrillBot/GrillBot.Web/assets/56552845/5ed96865-266b-40f2-b374-bbfdbf1739c5)

**Comment by Misha12** [comment]
Visibility of text "Zobrazit/Skrýt" is correct. There is an another bug. It's possible to click on the header when card is configured to be hidden.
