### ISSUE TITLE
User measures return error on load

### ISSUE THREAD

**Issue by solumath** [GrillBot/GrillBot.Web#29]
After loading https://private.grillbot.eu/admin/userMeasures i get this error
![image](https://github.com/GrillBot/GrillBot.Web/assets/56552845/29811f8a-c083-4644-bb00-6864d5d3ce0c)

**Comment by okurka12** [comment]
When going to said page, I get a similar error:
![image](https://github.com/user-attachments/assets/6271fdcb-0df9-44e8-a896-a50d9ddf6660)
