### ISSUE TITLE
Listing through audit log with page number

### ISSUE THREAD

**Issue by solumath** [GrillBot/GrillBot.Web#5]
I would welcome being able to give the number of page to get to instead of clicking only last and next when going through audit log.
![image](https://github.com/GrillBot/grillbot/assets/56552845/b6991957-1eb5-4d6a-8e10-623d375699cf)

**Comment by Misha12** [comment]
In the new version of web app pagination should be possible to set the page number using input. The new page should be automatically requested on the server.

![image](https://github.com/GrillBot/GrillBot.Web/assets/9041462/b0f3aa20-de48-40a9-a52f-a9a9f66f0ea6)
